
ny_taxi:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: de-zoomcamp-485821
      dataset: dbt_dev
      threads: 4
      keyfile: /path/to/your/service-account-key.json
      location: US
      
    prod:
      type: bigquery
      method: service-account
      project: de-zoomcamp-485821
      dataset: dbt_prod
      threads: 4
      keyfile: /path/to/your/service-account-key.json
      location: US